version: '3'
services:
  extension:
    image: kwil-extension:latest
    ports:
      - 50055:50051
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure

  kwil:
    image: kwildb/kwil:latest
    ports:
      - 50051:50051
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./config/kwil.env
    environment:
      - KWILD_EXTENSION_ENDPOINTS=extension:50051
    depends_on:
      - extension
    restart: on-failure